### ISSUE TITLE
non interactive installation not 100% non interactive

### ISSUE THREAD

**Issue by canariecaf** [canariecaf/idp-installer-CAF#30]
When choosing the non-interactive installation item in the GUI, the deploy_idp.sh still requires interactivity in the following spots:

1. The preflight check 'hit enter to continue'
2. the ok dialog to proceed with eduroam install
3. the dialog with 'successful eduroam install, now join the domain'

To be fully non-interactive the following needs to happen:
mitigation item:
1 - do not require entire, but fail to proceed if error state happens
2. - dialog to proceed can be skipped
3. - dialog can be skipped, but alert to end user and status.log that the user must join the machine to the domain should be there.  Documentation should also be updated for headless/non-interactive/unattended installation.

**Comment by cmann** [comment]
Found another issue, there's a unconditional ask for installing fticks when performing an upgrade. The fix will be included in the next pull request.

**Comment by canariecaf** [comment]
confirmed.
