### ISSUE TITLE
FW rules dosent save on Ubuntu

### ISSUE THREAD

**Issue by lordal** [canariecaf/idp-installer-CAF#46]
The file /etc/sysconfig/iptables does not exist on Ubuntu.
Branch: develop

**Comment by canariecaf** [comment]
Thanks Anders,
Doing a full rebuild of everything(master, develop, develop-Shibv3Support) to verify whether or not this was dealt with yet.

**Comment by canariecaf** [comment]
does not appear to still be a problem but will keep an eye out for it. 
Closing.
