### ISSUE TITLE
Function enableJettyOnRestart does not work on Ubuntu

### ISSUE THREAD

**Issue by lordal** [canariecaf/idp-installer-CAF#47]
Function enableJettyOnRestart only runs if $dist != "ubuntu"

Adding the following in the function would fix:
else
		update-rc.d jetty defaults

Branch: develop

**Comment by canariecaf** [comment]
Thanks Anders, 
Will check it out existence of problem after branches rebuild.

**Comment by canariecaf** [comment]
this does not appear to be a problem anymore, closing, re-open if it is
